# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.21.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.randint(0, 100, size=(30, 10, 2))
a

array([[[86, 78],
        [23, 19],
        [ 1, 43],
        [26, 76],
        [13, 42],
        [18, 25],
        [58,  3],
        [72, 18],
        [58, 42],
        [42, 15]],

       [[77, 83],
        [65,  5],
        [ 1, 84],
        [34, 99],
        [54,  6],
        [ 0, 47],
        [96,  9],
        [74, 64],
        [ 0, 79],
        [27, 23]],

       [[17, 39],
        [52, 13],
        [47, 38],
        [27,  7],
        [ 8, 23],
        [88, 28],
        [43, 38],
        [63, 41],
        [59, 80],
        [ 8, 54]],

       [[62,  1],
        [41, 37],
        [10, 71],
        [28, 99],
        [15, 47],
        [22, 71],
        [78, 97],
        [56, 42],
        [61, 65],
        [18, 41]],

       [[13, 18],
        [79, 40],
        [ 1, 18],
        [95, 97],
        [85,  8],
        [29, 39],
        [84, 99],
        [22, 53],
        [57, 48],
        [35, 72]],

       [[94, 54],
        [99, 76],
        [ 9, 74],
        [80, 27],
        [56, 80],


In [4]:
# Method 2
a = np.random.random((2,3,5))
a

array([[[0.73011553, 0.40168078, 0.25959969, 0.90168516, 0.21702286],
        [0.69544852, 0.75425298, 0.61657825, 0.38563671, 0.07706601],
        [0.60203027, 0.4576768 , 0.72318969, 0.89101752, 0.40088472]],

       [[0.8946848 , 0.83562469, 0.50786167, 0.55612462, 0.27134464],
        [0.79449768, 0.08529337, 0.18809792, 0.35434629, 0.25523461],
        [0.19208788, 0.04216799, 0.56923349, 0.81892591, 0.11617107]]])

In [5]:
# Method 3
a = np.random.sample((2, 3, 5))
a

array([[[0.23264436, 0.22146875, 0.97216383, 0.36645908, 0.65625409],
        [0.13896345, 0.33288225, 0.171618  , 0.07062614, 0.84527171],
        [0.01312103, 0.22189045, 0.28680641, 0.86145528, 0.64521649]],

       [[0.65939924, 0.58907297, 0.62199653, 0.35944146, 0.56451894],
        [0.96925176, 0.40686761, 0.37137264, 0.38725256, 0.84635687],
        [0.21747909, 0.22344552, 0.82046235, 0.63331852, 0.59456892]]])

#### 4. Print *a*.


In [6]:
# your code here
a

array([[[0.23264436, 0.22146875, 0.97216383, 0.36645908, 0.65625409],
        [0.13896345, 0.33288225, 0.171618  , 0.07062614, 0.84527171],
        [0.01312103, 0.22189045, 0.28680641, 0.86145528, 0.64521649]],

       [[0.65939924, 0.58907297, 0.62199653, 0.35944146, 0.56451894],
        [0.96925176, 0.40686761, 0.37137264, 0.38725256, 0.84635687],
        [0.21747909, 0.22344552, 0.82046235, 0.63331852, 0.59456892]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
# your code here
if a.size == b.size:
    print("They have the same size!")
else:
    print("They do not.")

They have the same size!


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print("No we are not able to add because even tho they have the same size they have different shapes.")
c=a+b

No we are not able to add because even tho they have the same size they have different shapes.


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
# your code here
c = np.transpose(b, axes=(1, 2, 0))
c.shape

(2, 3, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
# your code/answer here
d = a + c
d.shape

(2, 3, 5)

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a[0])
print(d[0])

[[0.23264436 0.22146875 0.97216383 0.36645908 0.65625409]
 [0.13896345 0.33288225 0.171618   0.07062614 0.84527171]
 [0.01312103 0.22189045 0.28680641 0.86145528 0.64521649]]
[[1.23264436 1.22146875 1.97216383 1.36645908 1.65625409]
 [1.13896345 1.33288225 1.171618   1.07062614 1.84527171]
 [1.01312103 1.22189045 1.28680641 1.86145528 1.64521649]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = a * c
print(e)

[[[0.23264436 0.22146875 0.97216383 0.36645908 0.65625409]
  [0.13896345 0.33288225 0.171618   0.07062614 0.84527171]
  [0.01312103 0.22189045 0.28680641 0.86145528 0.64521649]]

 [[0.65939924 0.58907297 0.62199653 0.35944146 0.56451894]
  [0.96925176 0.40686761 0.37137264 0.38725256 0.84635687]
  [0.21747909 0.22344552 0.82046235 0.63331852 0.59456892]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
if np.array_equal(e, a):
    print("Yes they're the same!")

Yes they're the same!


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(d_max)
print(d_min)
print(d_mean)

1.9721638339196361
1.0131210309856624
1.476721542798498


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
# your code here
f = np.empty([2, 3, 5])
f

array([[[0.23264436, 0.22146875, 0.97216383, 0.36645908, 0.65625409],
        [0.13896345, 0.33288225, 0.171618  , 0.07062614, 0.84527171],
        [0.01312103, 0.22189045, 0.28680641, 0.86145528, 0.64521649]],

       [[0.65939924, 0.58907297, 0.62199653, 0.35944146, 0.56451894],
        [0.96925176, 0.40686761, 0.37137264, 0.38725256, 0.84635687],
        [0.21747909, 0.22344552, 0.82046235, 0.63331852, 0.59456892]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
f = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        f += [25]
    if d_mean < x < d_max:
        f += [75]
    if x == d_mean:
        f += [50]
    if x == d_min:
        f += [0]
    if x == d_max:
        f += [100]
    
        
f = np.reshape(f, d.shape) 
print(f)

[[[ 25  25 100  25  75]
  [ 25  25  25  25  75]
  [  0  25  25  75  75]]

 [[ 75  75  75  25  75]
  [ 75  25  25  25  75]
  [ 25  25  75  75  75]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
# your code here
print(d)
print(f)

[[[1.23264436 1.22146875 1.97216383 1.36645908 1.65625409]
  [1.13896345 1.33288225 1.171618   1.07062614 1.84527171]
  [1.01312103 1.22189045 1.28680641 1.86145528 1.64521649]]

 [[1.65939924 1.58907297 1.62199653 1.35944146 1.56451894]
  [1.96925176 1.40686761 1.37137264 1.38725256 1.84635687]
  [1.21747909 1.22344552 1.82046235 1.63331852 1.59456892]]]
[[[ 25  25 100  25  75]
  [ 25  25  25  25  75]
  [  0  25  25  75  75]]

 [[ 75  75  75  25  75]
  [ 75  25  25  25  75]
  [ 25  25  75  75  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
j = []
for x in np.nditer(d):
    if d_min < x < d_mean:
        j += ['B']
    if d_mean < x < d_max:
        j += ['D']
    if x == d_mean:
        j += ['C']
    if x == d_min:
        j += ['A']
    if x == d_max:
        j += ['E']
    
j = np.reshape(j, d.shape) 
print(j)


[[['B' 'B' 'E' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['A' 'B' 'B' 'D' 'D']]

 [['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']]]


In [21]:
g = []

for elem in np.nditer(d):
	if d_mean > elem > d_min:
		g += 'B'
	elif d_mean < elem < d_max:
		g += 'D'
	elif elem == d_mean:
		g += 'C'
	elif elem == d_min:
		g += 'A'
	else:
		g += 'E'

g = np.reshape(g,(2,3,5))
print(g)
print(d)

[[['B' 'B' 'E' 'B' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['A' 'B' 'B' 'D' 'D']]

 [['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']]]
[[[1.23264436 1.22146875 1.97216383 1.36645908 1.65625409]
  [1.13896345 1.33288225 1.171618   1.07062614 1.84527171]
  [1.01312103 1.22189045 1.28680641 1.86145528 1.64521649]]

 [[1.65939924 1.58907297 1.62199653 1.35944146 1.56451894]
  [1.96925176 1.40686761 1.37137264 1.38725256 1.84635687]
  [1.21747909 1.22344552 1.82046235 1.63331852 1.59456892]]]
